### ISSUE TITLE
Can anyone explain what is "reservationUtilization=HEAVY" and FIXED?

### ISSUE THREAD

**Issue by zhangsimingshannonai** [Netflix/ice#298]
I don't know how to choose between HEAVY, FIXED...
Thanks.

**Comment by nfonrose** [comment]
Have you managed to solve this question? It depends on which type of RIs
you are mainly using.

This only applies to the "DBRWRT aka pre-CUR" era, but for AWS China, only
DBRWRT files are available for now.
So that does apply in your case.

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics for AWS, GCP and Azure powered
by NetflixOSS Ice
twitter - @nfonrose / @teevity
